Style
idungstanley/weather-app pull request #1
Opened 2022-06-26 03:06 UTC by idungstanley

- Create React app
- Add API to fetch region
- Add API to get details
-  Style
- Add router
- test

2022-06-26 04:46 UTC, roshan-bajgain reviewed
Hi @idungstanley , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter fails kindly fix it and submit the next reviewer.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-28 11:04 UTC, sinansevgi requested changes
Hi @idungstanley, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Search/Filter component works like a charm :+1: 

## Required Changes ♻️
- [ ] We should always document our code professionally. The project repository doesn't have a professional readme file. Please check the [microverse readme template](https://github.com/microverseinc/readme-template). You should use this template as guidance to create your readme file 
- [ ]  **You should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes**.  Please provide the video link in the pull request description.
The content of the video should include:
   - A description of the project.
   - A demo of the project features
   - You should also highlight some interesting piece of code or something you built that you are very proud of.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 11:04 UTC, sinansevgi commented on src/test/App.test.js
> +import React from 'react';
- [ ] For this project, we should also have integration tests for our components and methods. 
In integration testing, we test how our components work together. Currently, you only have snapshot tests. 
While creating the test please also consider these suggestions:
- You should use React Testing Library for testing your react components.
- You should mock your API calls to test your API-depended components.

2022-06-28 11:04 UTC, sinansevgi commented on src/service/ApiRequest.jsx
> +const getCountryData = async () => {
- [ ] For this project, we should create unit tests for pure functions in our Redux code.
Unit testing is the testing of each unit or an individual element of our applications. You should test that all of your pure functions work as expected with unit tests

2022-06-28 11:04 UTC, sinansevgi commented on README.md
> -# Weather-App
- [ ] You should  give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/) in Acknowledgements section of your readme file

2022-06-28 11:04 UTC, sinansevgi commented on README.md
> -# Weather-App
- [ ] The project should be deployed properly and you should also include a link to the deployed version of the project in the readme file

2022-06-28 16:46 UTC, sinansevgi requested changes
Hi @idungstanley, 

Kudos for the great presentation video. :+1: 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Happy Hacking! :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
Sinan Sevgi

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 16:46 UTC, sinansevgi commented on README.old.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] Great work but because of the naming error readme file doesn't get rendered on the repository page. You should rename this file to `README.md` to make it rendered as readme on your repository.

2022-06-28 16:46 UTC, sinansevgi commented on src/service/ApiRequest.jsx
> +const getCountryData = async () => {
- [ ] I couldn't find any commits/files changed related to this request. Please be sure that you have implemented the requested changes.

2022-06-28 16:46 UTC, sinansevgi commented on src/test/App.test.js
> +import React from 'react';
- [ ] I couldn't find any commits/files changed related to this request. Please be sure that you have implemented the requested changes.

2022-11-03 09:10 UTC, merged